name: Print Out Exec Context
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:
  workflow_call:
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printenv
          
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo ""
          echo "#############################################"
          echo "Event Payload"
          echo "Event Path: $GITHUB_EVENT_PATH"
          echo "#############################################"
          echo ""
          cat $GITHUB_EVENT_PATH
          echo ""
          echo "#############################################"
  github_script:
    runs-on: ubuntu-latest
    steps:
      - name: print-gh-script-context
        uses: actions/github-script@v6
        with:
          script: |
            console.log('*********************************************');
            console.log(context);
            console.log('*********************************************');