name: Print Out Exec Context
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printenv
          
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo ""
          echo "#############################################"
          echo "Event Payload"
          echo "Event Path: $GITHUB_EVENT_PATH"
          echo "#############################################"
          echo ""
          cat $GITHUB_EVENT_PATH
          echo ""
          echo "#############################################"